### ISSUE TITLE
google schoolar metadata

### ISSUE THREAD

**Issue by colomet** [Books4Languages/pressbooks-metadata#51]
1. https://scholar.google.com/intl/en/scholar/inclusion.html
2. https://webmasters.stackexchange.com/questions/72746/where-are-the-complete-set-of-highwire-press-metatags-defined
3. https://webmasters.stackexchange.com/questions/11613/indexing-for-google-scholar-which-tags-to-use

https://gist.github.com/greatislander/6428f1cb4e1a3fadeae7206872b1c038

Metadata for Book cover page (not root or post)

**Comment by colomet** [comment]
https://discourse.pressbooks.org/t/bibliographic-save-to-zotero/158/11

**Comment by colomet** [comment]
i think, to create metadata in the google way will be fast. and later we could create for zotero. in that way, we offer all the possibilities that matter.

we could use the default google schoolar citation_title https://scholar.google.com/intl/en/scholar/inclusion.html#indexing

**Comment by colomet** [comment]
https://thecustomizewindows.com/2015/04/google-scholar-metadata-guide-for-wordpress/

**Comment by masaka222** [comment]
These are the ones I added for now.
```html
<meta name = 'citation_journal_title' content = 'Metadata' />
<meta name = 'citation_author' content = 'Author' />
<meta name = 'citation_isbn' content = '1123' />
<meta name = 'citation_publisher' content = 'My Languages Skills' />
<meta name = 'citation_publication_date' content = '2017/04/02' />
```

I still need to check if it's the correct way to do it so I'm not closing the issue yet
