### ISSUE TITLE
functions s_md: to chage it to a more neutral name

### ISSUE THREAD

**Issue by colomet** [Books4Languages/pressbooks-metadata#59]
we have to extend the metadata. to google schoolar and other. s_md (shema metadata) is not a proper name. mayne something like: w_md

**Comment by colomet** [comment]
maybe extended metadata = e_md ??

**Comment by masaka222** [comment]
I would propose something similar to the plugin name, so that it will remain the same whatever path this plugin takes in the end. Like pm_ or pmd_

**Comment by colomet** [comment]
If in the future we use the plugin for a general wp installation (not just for pressbooks) we could not to change it, otherwise we will lose the save data, that´s why  i would like to have something general.

**Comment by colomet** [comment]
New name after a discusion : Metadata = mtdt

**Comment by colomet** [comment]
or to use the PB function in order to be able to export inside of their export file.
