### ISSUE TITLE
Category of books

### ISSUE THREAD

**Issue by colomet** [Books4Languages/pressbooks-metadata#62]
https://www.amazon.com/s/ref=lp_1_ex_n_1?rh=n%3A283155&bbn=283155&ie=UTF8&qid=1494249853

Amazon Main Categories of books
	•	Arts & Photography
	•	Biographies & Memoirs
	•	Business & Money
	•	Calendars
	•	Children's Books
	•	Christian Books & Bibles
	•	Comics & Graphic Novels
	•	Computers & Technology
	•	Cookbooks, Food & Wine
	•	Crafts, Hobbies & Home
	•	Education & Teaching
	•	Engineering & Transportation
	•	Gay & Lesbian
	•	Health, Fitness & Dieting
	•	History
	•	Humor & Entertainment
	•	Law
	•	Literature & Fiction 
	•	Medical Books
	•	Mystery, Thriller & Suspense
	•	Parenting & Relationships
	•	Politics & Social Sciences
	•	Reference
	•	Religion & Spirituality
	•	Romance
	•	Science & Math
	•	Science Fiction & Fantasy
	•	Self-Help
	•	Sports & Outdoors
	•	Teen & Young Adult
	•	Test Preparation
	•	Travel

**Comment by colomet** [comment]
http://schema.org/about ?

**Comment by masaka222** [comment]
It could be... But if our plugin is for educational purposes, we do something similar with the isbn field of study

**Comment by colomet** [comment]
we need such field for the Root theme. We need to create a filter of books. For my books we will use the metadat you did it. But for the other installations of PB, they need something general, and I don´t know what to do.

**Comment by colomet** [comment]
http://schema.org/genre ?

**Comment by masaka222** [comment]
genre seems better. About is too general I think

**Comment by colomet** [comment]
[BISAC_Subject_Headings.xls.zip](https://github.com/Books4Languages/pressbooks-metadata/files/983653/BISAC_Subject_Headings.xls.zip)

**Comment by masaka222** [comment]
There is a field for BISAC Subject Headings and it's already being used in the http://schema.org/about structured data from pressbooks. Maybe it's the same thing you want?

**Comment by colomet** [comment]
Yes, but now BISAC is an empty place for the codes. Too complicate, the people will not write the codes. We need something simple, a list of categories and then, the people will choose one.

**Comment by colomet** [comment]
into an independent plugin
https://github.com/Books4Languages/pressbooks-metadata-subject-category/issues/1
