### ISSUE TITLE
finishig the metadata for the chapter

### ISSUE THREAD

**Issue by colomet** [Books4Languages/pressbooks-metadata#9]
upgrade till all the Types from the class http://schema.org/ScholarlyArticle

To create metadata under the atomic design principles

**Comment by masaka222** [comment]
In version 0.5 we added:
- headline
- image
- wordCount
- author
- alternativeHeadline
- audience
- citation
- copyrightHolder
- copyrightYear
- datePublished
- dateModified
- discussionUrl
- editor
- inLanguage
- license
- locationCreated
- publisher
- timeRequired
- translator
- typicalAgeRange
